# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool: DevPool

steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'

# - script: VERSION_TAG=`git describe --tags` && echo "##vso[task.setvariable variable=VERSION_TAG]$VERSION_TAG"
#   displayName: Set the tag name as an environment variable

# - powershell: |
#    $CI_BUILD_TAG = git describe --tags
#    Write-Host "##vso[task.setvariable variable=CI_BUILD_TAG]$CI_BUILD_TAG"
#   displayName: 'Set the tag name as an environment variable'

# - powershell: |
#    $ver = $env:git describe --match build
#    Write-Host "##vso[task.setvariable variable=Version]$ver"
#   displayName: 'Update version to Tag'
#   condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))

# - script: echo $(Version)
#   displayName: 'Run a one-line script'

# - powershell: echo "##vso[task.setvariable variable=a;isOutput=true]10"
#   name: a_step


# - powershell: |
#    $ver = $env:BUILD_SOURCEBRANCH.remove(0, 10)
#    Write-Host "##vso[task.setvariable variable=Version]$ver"
#   displayName: 'Update version to Tag'
#   condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))


- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      $ver = Get-Location
      Write-Host $ver